FROM emscripten/emsdk:3.1.13
WORKDIR /root

RUN mkdir src && \
        cd src && \
        curl -L -O http://www.fftw.org/fftw-3.3.10.tar.gz && \
        tar xvzf fftw-3.3.10.tar.gz

CMD cd /root/src/fftw-3.3.10 && \
        emconfigure ./configure && \
        emmake make && \
        emcc .libs/libfftw3.a -o ../../lib/fftw3.wasm -s EXPORTED_FUNCTIONS='["fftw_execute","fftw_plan_dft","fftw_plan_dft_","fftw_plan_dft_","fftw_plan_dft_","fftw_plan_many_dft","fftw_plan_guru_dft","fftw_plan_guru_split_dft","fftw_plan_guru","fftw_plan_guru","fftw_execute_dft","fftw_execute_split_dft","fftw_plan_many_dft_r","fftw_plan_dft_r","fftw_plan_dft_r","fftw_plan_dft_r","fftw_plan_dft_r","fftw_plan_many_dft_c","fftw_plan_dft_c","fftw_plan_dft_c","fftw_plan_dft_c","fftw_plan_dft_c","fftw_plan_guru_dft_r","fftw_plan_guru_dft_c","fftw_plan_guru_split_dft_r","fftw_plan_guru_split_dft_c","fftw_plan_guru","fftw_plan_guru","fftw_plan_guru","fftw_plan_guru","fftw_execute_dft_r","fftw_execute_dft_c","fftw_execute_split_dft_r","fftw_execute_split_dft_c","fftw_plan_many_r","fftw_plan_r","fftw_plan_r","fftw_plan_r","fftw_plan_r","fftw_plan_guru_r","fftw_plan_guru","fftw_execute_r","fftw_destroy_plan","fftw_cleanup","fftw_set_timelimit","fftw_plan_with_nthreads","fftw_init_threads","fftw_cleanup_threads","fftw_make_planner_thread_safe","fftw_print_plan","fftw_sprint_plan","fftw_malloc","fftw_alloc_real","fftw_free","fftw_flops","fftw_estimate_cost","fftw_cost","fftwf_execute","fftwf_plan_dft","fftwf_plan_dft_","fftwf_plan_dft_","fftwf_plan_dft_","fftwf_plan_many_dft","fftwf_plan_guru_dft","fftwf_plan_guru_split_dft","fftwf_plan_guru","fftwf_plan_guru","fftwf_execute_dft","fftwf_execute_split_dft","fftwf_plan_many_dft_r","fftwf_plan_dft_r","fftwf_plan_dft_r","fftwf_plan_dft_r","fftwf_plan_dft_r","fftwf_plan_many_dft_c","fftwf_plan_dft_c","fftwf_plan_dft_c","fftwf_plan_dft_c","fftwf_plan_dft_c","fftwf_plan_guru_dft_r","fftwf_plan_guru_dft_c","fftwf_plan_guru_split_dft_r","fftwf_plan_guru_split_dft_c","fftwf_plan_guru","fftwf_plan_guru","fftwf_plan_guru","fftwf_plan_guru","fftwf_execute_dft_r","fftwf_execute_dft_c","fftwf_execute_split_dft_r","fftwf_execute_split_dft_c","fftwf_plan_many_r","fftwf_plan_r","fftwf_plan_r","fftwf_plan_r","fftwf_plan_r","fftwf_plan_guru_r","fftwf_plan_guru","fftwf_execute_r","fftwf_destroy_plan","fftwf_cleanup","fftwf_set_timelimit","fftwf_plan_with_nthreads","fftwf_init_threads","fftwf_cleanup_threads","fftwf_make_planner_thread_safe","fftwf_print_plan","fftwf_sprint_plan","fftwf_malloc","fftwf_alloc_real","fftwf_alloc_complex","fftwf_free","fftwf_flops","fftwf_estimate_cost","fftwf_cost"]' --no-entry && \
        # emcc .libs/libfftw3.a -o ../../lib/fftw3.wasm -s EXPORTED_FUNCTIONS='["fftw_execute","fftw_plan_dft","fftw_plan_dft_","fftw_plan_dft_","fftw_plan_dft_","fftw_plan_many_dft","fftw_plan_guru_dft","fftw_plan_guru_split_dft","fftw_plan_guru","fftw_plan_guru","fftw_execute_dft","fftw_execute_split_dft","fftw_plan_many_dft_r","fftw_plan_dft_r","fftw_plan_dft_r","fftw_plan_dft_r","fftw_plan_dft_r","fftw_plan_many_dft_c","fftw_plan_dft_c","fftw_plan_dft_c","fftw_plan_dft_c","fftw_plan_dft_c","fftw_plan_guru_dft_r","fftw_plan_guru_dft_c","fftw_plan_guru_split_dft_r","fftw_plan_guru_split_dft_c","fftw_plan_guru","fftw_plan_guru","fftw_plan_guru","fftw_plan_guru","fftw_execute_dft_r","fftw_execute_dft_c","fftw_execute_split_dft_r","fftw_execute_split_dft_c","fftw_plan_many_r","fftw_plan_r","fftw_plan_r","fftw_plan_r","fftw_plan_r","fftw_plan_guru_r","fftw_plan_guru","fftw_execute_r","fftw_destroy_plan","fftw_cleanup","fftw_set_timelimit","fftw_plan_with_nthreads","fftw_init_threads","fftw_cleanup_threads","fftw_make_planner_thread_safe","fftw_print_plan","fftw_sprint_plan","fftw_malloc","fftw_alloc_real","fftw_alloc_complex","fftw_free","fftw_flops","fftw_estimate_cost","fftw_cost","fftw_alignment_of","fftwf_execute","fftwf_plan_dft","fftwf_plan_dft_","fftwf_plan_dft_","fftwf_plan_dft_","fftwf_plan_many_dft","fftwf_plan_guru_dft","fftwf_plan_guru_split_dft","fftwf_plan_guru","fftwf_plan_guru","fftwf_execute_dft","fftwf_execute_split_dft","fftwf_plan_many_dft_r","fftwf_plan_dft_r","fftwf_plan_dft_r","fftwf_plan_dft_r","fftwf_plan_dft_r","fftwf_plan_many_dft_c","fftwf_plan_dft_c","fftwf_plan_dft_c","fftwf_plan_dft_c","fftwf_plan_dft_c","fftwf_plan_guru_dft_r","fftwf_plan_guru_dft_c","fftwf_plan_guru_split_dft_r","fftwf_plan_guru_split_dft_c","fftwf_plan_guru","fftwf_plan_guru","fftwf_plan_guru","fftwf_plan_guru","fftwf_execute_dft_r","fftwf_execute_dft_c","fftwf_execute_split_dft_r","fftwf_execute_split_dft_c","fftwf_plan_many_r","fftwf_plan_r","fftwf_plan_r","fftwf_plan_r","fftwf_plan_r","fftwf_plan_guru_r","fftwf_plan_guru","fftwf_execute_r","fftwf_destroy_plan","fftwf_cleanup","fftwf_set_timelimit","fftwf_plan_with_nthreads","fftwf_init_threads","fftwf_cleanup_threads","fftwf_make_planner_thread_safe","fftwf_print_plan","fftwf_sprint_plan","fftwf_malloc","fftwf_alloc_real","fftwf_alloc_complex","fftwf_free","fftwf_flops","fftwf_estimate_cost","fftwf_cost","fftwf_alignment_of"]' --no-entry && \
        cp a.wasm /root/lib/a.wasm


# "fftw_execute","fftw_plan_dft","fftw_plan_dft_","fftw_plan_dft_","fftw_plan_dft_","fftw_plan_many_dft","fftw_plan_guru_dft","fftw_plan_guru_split_dft","fftw_plan_guru","fftw_plan_guru","fftw_execute_dft","fftw_execute_split_dft","fftw_plan_many_dft_r","fftw_plan_dft_r","fftw_plan_dft_r","fftw_plan_dft_r","fftw_plan_dft_r","fftw_plan_many_dft_c","fftw_plan_dft_c","fftw_plan_dft_c","fftw_plan_dft_c","fftw_plan_dft_c","fftw_plan_guru_dft_r","fftw_plan_guru_dft_c","fftw_plan_guru_split_dft_r","fftw_plan_guru_split_dft_c","fftw_plan_guru","fftw_plan_guru","fftw_plan_guru","fftw_plan_guru","fftw_execute_dft_r","fftw_execute_dft_c","fftw_execute_split_dft_r","fftw_execute_split_dft_c","fftw_plan_many_r","fftw_plan_r","fftw_plan_r","fftw_plan_r","fftw_plan_r","fftw_plan_guru_r","fftw_plan_guru","fftw_execute_r","fftw_destroy_plan","fftw_cleanup","fftw_set_timelimit","fftw_plan_with_nthreads","fftw_init_threads","fftw_cleanup_threads","fftw_make_planner_thread_safe","fftw_print_plan","fftw_sprint_plan","fftw_malloc","fftw_alloc_real","fftw_alloc_complex","fftw_free","fftw_flops","fftw_estimate_cost","fftw_cost","fftw_alignment_of","fftwf_execute","fftwf_plan_dft","fftwf_plan_dft_","fftwf_plan_dft_","fftwf_plan_dft_","fftwf_plan_many_dft","fftwf_plan_guru_dft","fftwf_plan_guru_split_dft","fftwf_plan_guru","fftwf_plan_guru","fftwf_execute_dft","fftwf_execute_split_dft","fftwf_plan_many_dft_r","fftwf_plan_dft_r","fftwf_plan_dft_r","fftwf_plan_dft_r","fftwf_plan_dft_r","fftwf_plan_many_dft_c","fftwf_plan_dft_c","fftwf_plan_dft_c","fftwf_plan_dft_c","fftwf_plan_dft_c","fftwf_plan_guru_dft_r","fftwf_plan_guru_dft_c","fftwf_plan_guru_split_dft_r","fftwf_plan_guru_split_dft_c","fftwf_plan_guru","fftwf_plan_guru","fftwf_plan_guru","fftwf_plan_guru","fftwf_execute_dft_r","fftwf_execute_dft_c","fftwf_execute_split_dft_r","fftwf_execute_split_dft_c","fftwf_plan_many_r","fftwf_plan_r","fftwf_plan_r","fftwf_plan_r","fftwf_plan_r","fftwf_plan_guru_r","fftwf_plan_guru","fftwf_execute_r","fftwf_destroy_plan","fftwf_cleanup","fftwf_set_timelimit","fftwf_plan_with_nthreads","fftwf_init_threads","fftwf_cleanup_threads","fftwf_make_planner_thread_safe","fftwf_print_plan","fftwf_sprint_plan","fftwf_malloc","fftwf_alloc_real","fftwf_alloc_complex","fftwf_free","fftwf_flops","fftwf_estimate_cost","fftwf_cost","fftwf_alignment_of"
